### ISSUE TITLE
Make Possible Manual Feedback from Users

### ISSUE THREAD

**Issue by Mranfevb92** [coding-is-for-losers/seo-audit#27]
Based on [this comment](https://webrisagency.slack.com/archives/C01C2GR0VDM/p1606947202016600) from Ryan. He gave two examples but we could think of other scenarios where this option would be helpful and include them in the discussion below: 

* One time-action recommendations: Give the user the ability to "ignore" certain actions so they don't appear repeatedly in each month's report. 

* Page Type Classification: Give the user the option to override/change the original classification. This ties with the discussion on page type classification issue #19

**Comment by codingisforlosers** [comment]
Accepting manual feedback requires mods in a few places (using [this v2 Workbook template as an example](https://docs.google.com/spreadsheets/d/1fIVEYN7mlj2fyeq5ySmz-zsuiquoylLYX0iW4QoZ0LU/edit#gid=21548238)):

- [x] 0: Summary tab
Ability to query general data about a user's sites into the workbook, to give them a high-level view of sites they manage, counts of action recommendations in various statuses, and page type counts for those sites.  

This would serve as a quick pulse report, to see what areas need attention / review for each site.

These will be used to populate dropdown menus throughout tabs on the workbook, and likely will require new models to be built (similar to the `actions_count` model).

- [x] 1: Selecting rows to modify (Page Type Reviews / Action Updates tabs)
Based on values on the summary tab, the user will select a segment of pages to review (either for actions or page types).

This will rely on a series of dropdown menus (populated with options from step 0), which will combine to form queries that are then pulled from BQ.  

For example, a user can select to review actions that are status = 'Unreviewed', action_type = 'On-page', site = 'CIFL', and page_type = 'Blog'.   

We can base these queries off of the existing queries for On-page / Off-page / Technical actions. 

- [ ] 2: Writing page type values / action recommendation statuses back to BQ
After a user pulls in values for modification, we'll provide columns where they can update values.

For example, an action recommendation could have its status modified:

_Tentative status options -> Unreviewed, Not relevant, To schedule, Working, Completed, Blocked_ 

We'll provide an Apps Script submenu item (Update Actions in BQ, Update Page Types in BQ), that'd write these values back to BigQuery.

A user *could* use this process to add actions that weren't recommended, as long as they format data correctly and provide an action 'type' (on-page/off-page/technical/architectural).

These will write to a specific table (`action_updates`, `page_type_updates`) that can be processed and then joined into action recommendations.

- [ ] 3: Incorporate these updates into models
All actions will, by default, be set to status = 'Unreviewed'.  

When a user overrides an action status (or page type), that override will be joined into the relevant table (probably `actions_proc` or `actions_hierarchy`).  

We may want to make these tables materialized views rather than tables, so that the feedback with the workbook could be direct (ie someone can pull statuses, write updates, and then pull back to Sheets and it'll reflect updates).

**Comment by Mranfevb92** [comment]
@codingisforlosers These steps are clear so I can begin making the changes. I'll probably need a hand when modifying the script, but will let you know once this is ready so you can get involved. 

My only big doubt involves step 2 and 3: 

* I understand that on step 2 we'll push to BQ the updates the user makes to page_type or actions (setting tables like `action_updates` and `page_type_updates `). How will we make the join between these updates tables and the `actions_proc` or `action_hierarchy` so the changes can be pulled back immediately? Can we script dbt runs from google script? Or do we use scheduled queries in BQ to react anytime new data is pushed to the updates tables?

**Comment by codingisforlosers** [comment]
> @codingisforlosers These steps are clear so I can begin making the changes. I'll probably need a hand when modifying the script, but will let you know once this is ready so you can get involved.
> 
> My only big doubt involves step 2 and 3:
> 
> * I understand that on step 2 we'll push to BQ the updates the user makes to page_type or actions (setting tables like `action_updates` and `page_type_updates `). How will we make the join between these updates tables and the `actions_proc` or `action_hierarchy` so the changes can be pulled back immediately? Can we script dbt runs from google script? Or do we use scheduled queries in BQ to react anytime new data is pushed to the updates tables?

Think we'll need to use materialized views here in dbt, which basically run the model on the fly anytime data is queried.

**Comment by codingisforlosers** [comment]
@Mranfevb92 played with #0 (summary tab) a bit, and it seems like splitting out page types / action recommendations into separate 'summary' tabs makes the most sense - see here:

https://docs.google.com/spreadsheets/d/1fIVEYN7mlj2fyeq5ySmz-zsuiquoylLYX0iW4QoZ0LU/edit#gid=21548238

these are really two separate review flows, so feel like the more we can keep tabs to a single purpose, the less confused people will be.

**Comment by Mranfevb92** [comment]
@codingisforlosers set up the queries to pull the data for review based on the summary tabs, organized the _page_type_review_ and _action_review_ tabs so they are ready for input, and added two extra tabs: _action_review_push_bq_ and _page_type_review_push_bq_, which would be the ones to push to BQ with the changes made on the review tabs. 

Also, set up this PR [](https://github.com/coding-is-for-losers/qr-wqa/pull/12) with a first commit that creates the `page_type_updates` and `action_updates` tables for the first run of the models. Will use this same PR to push the changes to join the updates tables to create a materialized view we can pull back to sheets.

**Comment by codingisforlosers** [comment]
Workbook ready here:
https://docs.google.com/spreadsheets/d/1fIVEYN7mlj2fyeq5ySmz-zsuiquoylLYX0iW4QoZ0LU/edit#gid=1599954048

Closing this issue out for now
